# Base
FROM python:3.10-buster
RUN apt-get update && \
    apt-get install -y libdbus-1-dev build-essential musl-dev bash
RUN pip install dbus-python

# Apprise Setup
VOLUME ["/apprise"]
WORKDIR /apprise
COPY requirements.txt /
COPY dev-requirements.txt /
ENV PYTHONPATH /apprise
ENV PYTHONPYCACHEPREFIX /apprise/__pycache__/py310


RUN pip install -r /requirements.txt -r /dev-requirements.txt
