from typing import Any

from .. import ContentLocation

class AttachBase:
    max_detect_buffer_size: int
    unknown_mimetype: str
    unknown_filename: str
    unknown_filename_extension: str
    strict: bool
    max_file_size: int
    location: ContentLocation
    template_args: dict[str, Any]
    def __init__(
        self,
        name: str | None = ...,
        mimetype: str | None = ...,
        cache: bool | None = ...,
        **kwargs: Any,
    ) -> None: ...
    @property
    def path(self) -> str | None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def mimetype(self) -> str | None: ...
    def exists(self) -> bool: ...
    def invalidate(self) -> None: ...
    def download(self) -> bool: ...
    @staticmethod
    def parse_url(url: str, verify_host: bool = ...) -> dict[str, Any]: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
