# .github/workflows/lint.yml
name: Run Lint Checks

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tox
        run: python -m pip install tox

      - name: Run Ruff lint check
        run: tox -e lint
